### ISSUE TITLE
Error decompressing Swift download

### ISSUE THREAD

**Issue by moubry** [sinoru/actions-setup-swift#138]
For this workflow file:

```
name: Swift

on:
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftAndSwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: 'latest'
      - name: GitHub Actions for SwiftLint
        uses: sinoru/actions-swiftlint@v6
      - uses: sinoru/actions-swift@v1
        with:
          swift-image-tag: 'latest'
          args: 'build'
      - uses: sinoru/actions-swift@v1
        with:
          swift-image-tag: 'latest'
          args: 'test'
```

I'm getting this error:

```
Install swift
  /usr/bin/bash -c swiftenv install -s latest
  Downloading https://download.swift.org/swift-latest-release/ubuntu2204/swift-latest-RELEASE/swift-latest-RELEASE-ubuntu22.04.tar.gz
  /tmp/swiftenv-latest-runner ~/work/chat-ios/chat-ios
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  100   297  100   297    0     0    611      0 --:--:-- --:--:-- --:--:--   612
  
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  100   257  100   257    0     0    334      0 --:--:-- --:--:-- --:--:--  1093
  
  100   146  100   146    0     0    118      0  0:00:01  0:00:01 --:--:--   118
  
  gzip: stdin: not in gzip format
  tar: Child returned status 1
  tar: Error is not recoverable: exiting now
  Error: The process '/usr/bin/bash' failed with exit code 2
```

It seems to be failing at the `inoru/actions-setup-swift@v2` because it's getting the download in an unexpected format?
